name: "Grotesk CV"
description: "A clean, professional CV template using the official grotesk-cv package"
version: "1.0.5"
author: "Ásbjörn Skarphéðinsson"
features:
    - "Clean modern design"
    - "Two-column layout"
    - "FontAwesome icons"
    - "Professional typography"
    - "Official grotesk-cv package"
    - "TOML configuration"

main_function: "cv"
data_format: "toml"

data_extractor:
    name_path: ["personal", "first_name"]
    email_path: ["personal", "info", "email", "label"]
    fallback_name: "Unknown"

fields:
    personal:
        type: object
        required: true
        label: "Personal Information"
        description: "Your personal details and contact information"
        fields:
            first_name:
                type: string
                required: true
                label: "First Name"
                description: "Your first name"
            last_name:
                type: string
                required: true
                label: "Last Name"
                description: "Your last name"
            profile_image:
                type: string
                required: false
                label: "Profile Image"
                description: "Filename of your profile image (should be in img/ folder)"
                default: "portrait.png"
            language:
                type: string
                required: true
                label: "Language"
                description: "Primary language code (en, es)"
                default: "en"
            include_icons:
                type: boolean
                required: false
                label: "Include Icons"
                description: "Whether to include FontAwesome icons"
                default: false
            info:
                type: object
                required: true
                label: "Contact Information"
                fields:
                    address:
                        type: string
                        required: false
                        label: "Address"
                        description: "Your current address or location"
                    telephone:
                        type: string
                        required: false
                        label: "Phone Number"
                        description: "Your phone number"
                    email:
                        type: object
                        required: true
                        label: "Email"
                        fields:
                            link:
                                type: string
                                required: true
                                label: "Email Link"
                                pattern: "^mailto:[^@]+@[^@]+\\.[^@]+$"
                                description: "Email link (e.g., mailto:your@email.com)"
                            label:
                                type: string
                                required: true
                                label: "Email Display"
                                description: "Email address to display"
                    linkedin:
                        type: object
                        required: false
                        label: "LinkedIn"
                        fields:
                            link:
                                type: string
                                required: true
                                label: "LinkedIn URL"
                                pattern: "^https?://.*linkedin\\.com.*"
                            label:
                                type: string
                                required: true
                                label: "LinkedIn Display"
                    github:
                        type: object
                        required: false
                        label: "GitHub"
                        fields:
                            link:
                                type: string
                                required: true
                                label: "GitHub URL"
                                pattern: "^https?://.*github\\.com.*"
                            label:
                                type: string
                                required: true
                                label: "GitHub Display"
            icon:
                type: object
                required: false
                label: "Icon Settings"
                fields:
                    address:
                        type: string
                        default: "house"
                    telephone:
                        type: string
                        default: "phone"
                    email:
                        type: string
                        default: "envelope"
                    linkedin:
                        type: string
                        default: "linkedin"
                    github:
                        type: string
                        default: "github"
                    homepage:
                        type: string
                        default: "globe"

    layout:
        type: object
        required: false
        label: "Layout Settings"
        description: "Customize the appearance of your CV"
        fields:
            fill_color:
                type: string
                required: false
                label: "Background Color"
                description: "Hex color code for background (e.g., #f4f1eb)"
                default: "#f4f1eb"
            paper_size:
                type: string
                required: false
                label: "Paper Size"
                default: "a4"
            accent_color:
                type: string
                required: false
                label: "Accent Color"
                description: "Hex color code for accents (e.g., #d4d2cc)"
                default: "#d4d2cc"
            left_pane_width:
                type: string
                required: false
                label: "Left Column Width"
                description: "Width of left column as percentage (e.g., 71%)"
                default: "71%"
            text:
                type: object
                required: false
                label: "Text Settings"
                fields:
                    font:
                        type: string
                        required: false
                        label: "Font Family"
                        default: "HK Grotesk"
                    size:
                        type: string
                        required: false
                        label: "Font Size"
                        default: "10pt"
                    cover_letter_size:
                        type: string
                        required: false
                        label: "Cover Letter Font Size"
                        default: "11pt"
                    color:
                        type: object
                        required: false
                        label: "Text Colors"
                        fields:
                            light:
                                type: string
                                required: false
                                label: "Light Text Color"
                                default: "#ededef"
                            medium:
                                type: string
                                required: false
                                label: "Medium Text Color"
                                default: "#78787e"
                            dark:
                                type: string
                                required: false
                                label: "Dark Text Color"
                                default: "#3c3c42"

    language:
        type: object
        required: false
        label: "Language Settings"
        fields:
            en:
                type: object
                required: false
                label: "English"
                fields:
                    subtitle:
                        type: string
                        required: false
                        label: "Professional Subtitle"
                        default: "Software Engineer with a knack for human-friendly AI solutions"
                    cv_document_name:
                        type: string
                        required: false
                        label: "CV Document Name"
                        default: "Resume"
                    cover_letter_document_name:
                        type: string
                        required: false
                        label: "Cover Letter Document Name"
                        default: "Cover letter"
            es:
                type: object
                required: false
                label: "Spanish"
                fields:
                    subtitle:
                        type: string
                        required: false
                        label: "Professional Subtitle"
                        default: "Ingeniero de software con un talento para soluciones de IA amigables para humanos"
                    cv_document_name:
                        type: string
                        required: false
                        label: "CV Document Name"
                        default: "CV"
                    cover_letter_document_name:
                        type: string
                        required: false
                        label: "Cover Letter Document Name"
                        default: "Carta de motivación"

    section:
        type: object
        required: false
        label: "Section Icons"
        fields:
            icon:
                type: object
                required: false
                label: "Section Icons"
                fields:
                    education:
                        type: string
                        default: "graduation-cap"
                    experience:
                        type: string
                        default: "briefcase"
                    languages:
                        type: string
                        default: "language"
                    other_experience:
                        type: string
                        default: "wrench"
                    personal:
                        type: string
                        default: "brain"
                    profile:
                        type: string
                        default: "id-card"
                    references:
                        type: string
                        default: "users"
                    skills:
                        type: string
                        default: "cogs"

    import:
        type: object
        required: false
        label: "Import Settings"
        fields:
            fontawesome:
                type: string
                required: false
                label: "FontAwesome Package"
                default: "@preview/fontawesome:0.5.0"

template_files:
    - "cv.typ"
    - "info.toml"
    - "content/"
    - "img/"
