services:
    mycv-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "7070:7070"
        environment:
            - PORT=7070
        restart: unless-stopped
        healthcheck:
            test:
                [
                    "CMD",
                    "wget",
                    "--no-verbose",
                    "--tries=1",
                    "--spider",
                    "http://localhost:7070/",
                ]
            timeout: 5s
            interval: 30s
            retries: 3
            start_period: 40s
