version: '3'

tasks:
  # Run templ generation in watch mode
  templ:
    desc: Run templ generation in watch mode
    cmd: templ generate --watch --proxy="http://localhost:8090" --open-browser=false

  # Run air for Go hot reload
  server:
    desc: Run air for Go hot reload
    cmd: |
      air \
      --build.cmd "go build -o tmp/bin/main ./main.go" \
      --build.bin "tmp/bin/main" \
      --build.delay "100" \
      --build.exclude_dir "node_modules" \
      --build.include_ext "go" \
      --build.stop_on_error "false" \
      --misc.clean_on_exit true

  # Watch Tailwind CSS changes
  tailwind:
    desc: Watch Tailwind CSS changes
    cmd: tailwindcss -i ./assets/css/input.css -o ./assets/css/output.css --watch

  # Start development server with all watchers
  dev:
    desc: Start development server with all watchers
    deps: [tailwind, templ, server]
    cmd: echo "Development environment started with all watchers"
